parameters:
#    user_blog.example.class: User\BlogBundle\Example

services:
#    user_blog.example:
#        class: %user_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
